### ISSUE TITLE
question for running on philosopher v3.2.3

### ISSUE THREAD

**Issue by clin888** [Nesvilab/philosopher#120]
1) GitHub unreachable for the moment, can't check for versions right now.?
2) A meta data folder was found and will not be overwritten
3) The current Workspace is corrupted or was created with an older version. Please remove it and create a new one. (I am not sure this is due to incomplete installation on our IT group or new version of philosopher)

Thank you for help,

**Comment by hayse1** [comment]
Hi clin888, 1 and 2 are warnings that you don't need to worry about. For 3, did your process crash? Try removing the ".meta" folder and re-running the commands.

**Comment by clin888** [comment]
Thanks, I rerun it, no crash but no output either....
Should I ask our IT to reinstall v3.2.3?
please help,

Thanks again

**Comment by hayse1** [comment]
Can you copy & paste the log from executing the commands here?

**Comment by clin888** [comment]
clin@gizmoj35:~philosopher_linux/new_test_1$ philosopher pipeline --config philosopher_linux/new_test_1/philosopher_323.yml philosopher_linux/new_test_1
WARN[0000] The current Workspace is corrupted or was created with an older version. Please remove it and create a new one
INFO[11:18:31] Executing Pipeline  v3.2.3
INFO[11:18:31] Initiating the workspace on philosopher_linux/new_test_1
WARN[11:18:31] GitHub unreachable for the moment, can't check for versions right now.
INFO[11:18:31] Creating workspace
INFO[11:18:31] Processing database
INFO[11:18:34] Done

**Comment by hayse1** [comment]
Are you running Philosopher pipeline? It looks like you need to select the commands you want to run, only the `workspace` and `database` commands are selected in the default config .yml file:

```
commands:
  workspace: yes                               # manage the experiment workspace for the analysis
  database: yes                                # target-decoy database formatting
  comet: no                                    # peptide spectrum matching with Comet
  msfragger: no                                # peptide spectrum matching with MSFragger
  peptideprophet: no                           # peptide assignment validation
  ptmprophet: no                               # PTM site localization
  proteinprophet: no                           # protein identification validation
  filter: no                                   # statistical filtering, validation and False Discovery Rates assessment
  freequant: no                                # label-free Quantification
  labelquant: no                               # isobaric Labeling-Based Relative Quantification
  bioquant: no                                 # protein report based on Uniprot protein clusters
  report: no                                   # multi-level reporting for both narrow-searches and open-searches
  abacus: no                                   # combined analysis of LC-MS/MS results
  tmtintegrator: no                            # integrates channel abundances from multiple TMT samples
```

Please see the Philosopher documentation (https://github.com/Nesvilab/philosopher/wiki) for tutorials and more information. Depending on what type of analyses you want to run, you may also consider using FragPipe (http://fragpipe.nesvilab.org/).

Best,
Sarah
